version: '3.4'

services:
  sit3237372023t1prac5p:
    image: sit3237372023t1prac5p
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3040:3040
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "week4_code.js"]
